spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/observacao}
spring.data.mongodb.database=${MONGODB_DATABASE:observacao}
spring.data.mongodb.auto-index-creation=true

server.port=${SERVER_PORT:8080}